services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "8501:8501"

  backend:
    build:
      context: ./logistical_regression
    ports:
      - "8000:8000"
    volumes:
      - ./logistical_regression:/logistical_regression
      - ./Dataset:/Dataset