import os

MIDI_DIR = None
MP3_VOCALS_DIR = None
MIDI_VOCALS_DIR = None
MATCH_SCORES_PATH = None

MODELS_DIR = None
PREDICTIONS_DIR = None
FEATURES_DIR = None

MAX_PROCESSES = int(os.getenv("MAX_PROCESSES", 4))
MAX_LOADED_MODELS = int(os.getenv("MAX_LOADED_MODELS", 2))